include: package:flutter_lints/flutter.yaml

# Additional lint rules for this project
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - prefer_final_fields
    - use_key_in_widget_constructors
