name: appainter_minimal
description: A minimal Flutter app for creating and customizing Material Design 3 themes

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1
  file_picker: ^6.1.1
  google_fonts: ^6.1.0
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.1
  json_annotation: ^4.9.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
